# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogincomponents():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logincomponents(self):
    self.driver.get("https://sinyora.ru/administrator/?attempt=1")
    element = self.driver.find_element(By.CSS_SELECTOR, ".control-group:nth-child(1) .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "mod-login-username").click()
    self.driver.find_element(By.ID, "mod-login-username").send_keys("admin")
    self.driver.find_element(By.ID, "element-box").click()
    self.driver.find_element(By.ID, "mod-login-password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Компоненты").click()
    element = self.driver.find_element(By.LINK_TEXT, "JoomShopping")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "JoomShopping").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) img").click()
    self.driver.execute_script("window.scrollTo(0,29.03333282470703)")
    element = self.driver.find_element(By.ID, "limit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "limit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "limit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "limit").click()
    dropdown = self.driver.find_element(By.ID, "limit")
    dropdown.find_element(By.XPATH, "//option[. = '100']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#limit > option:nth-child(8)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#year_chzn b").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active-result:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#month_chzn b").click()
    self.driver.find_element(By.CSS_SELECTOR, "#month_chzn input").send_keys("10")
    self.driver.find_element(By.CSS_SELECTOR, "#month_chzn input").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.LINK_TEXT, "Последнее изменение")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#day_chzn span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#day_chzn input").send_keys("09")
    self.driver.find_element(By.CSS_SELECTOR, "#day_chzn input").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, ".control > .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".control .icon-search").click()
    self.driver.find_element(By.LINK_TEXT, "Меню пользователя").click()
    self.driver.find_element(By.LINK_TEXT, "Выход").click()
    self.driver.find_element(By.ID, "mod-login-username").send_keys("admin")
  
